version: '3.8'

services:
  redis-test:
    image: redis:7-alpine
    container_name: redis-test
    ports:
      - "6380:6379"
    command: redis-server --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      
  postgres-test:
    image: postgres:16-alpine
    container_name: postgres-test
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d testdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: src/Dockerfile-test
    depends_on:
      redis-test:
        condition: service_healthy
      postgres-test:
        condition: service_healthy
    #environment:
      #REDIS_CONNECTION_STRING: "redis-test:6379,allowAdmin=true,abortConnect=false"
      #POSTGRES_CONNECTION_STRING: "Host=postgres-test;Port=5432;Database=testdb;Username=testuser;Password=testpass"
    volumes:
      - ./test-results:/app/test-results